import { GoogleGenAI, Type, Modality } from "@google/genai";

let ai: GoogleGenAI;

const getAi = () => {
    if (!ai) {
        if (!process.env.API_KEY) {
            throw new Error("API_KEY environment variable not set");
        }
        ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    }
    return ai;
}

export const generateBlogPost = async (topic: string, keyword: string, length: string, tone: string, customInstructions: string) => {
    const ai = getAi();

    const blogLengthMap: { [key: string]: string } = {
        short: 'around 300 words',
        medium: 'around 800 words',
        long: 'around 1500 words',
    };

    const prompt = `
        Generate a high-quality, SEO-optimized blog post based on the following details.
        The output must be a JSON object with two keys: "title" (a string) and "content" (a string of well-formatted HTML).
        The HTML content should use appropriate tags like <h1>, <h2>, <p>, <ul>, <li>, <strong>, etc. Do not include <html> or <body> tags.

        - **Topic:** ${topic}
        - **Primary SEO Keyword:** ${keyword} (This keyword should be naturally integrated into the title, headings, and body text.)
        - **Desired Length:** ${blogLengthMap[length]}
        - **Writing Tone:** ${tone}
        - **Custom Instructions:** ${customInstructions || 'None'}

        Please ensure the blog post is engaging, informative, and well-structured.
    `;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-pro',
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    title: { type: Type.STRING },
                    content: { type: Type.STRING }
                },
                required: ['title', 'content']
            },
            thinkingConfig: { thinkingBudget: 32768 }
        }
    });
    
    // The response text is already a JSON string because of responseMimeType
    const jsonString = response.text.trim();
    return JSON.parse(jsonString);
};

export const generateImage = async (prompt: string, aspectRatio: string): Promise<string> => {
    const ai = getAi();
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
            numberOfImages: 1,
            outputMimeType: 'image/png',
            aspectRatio: aspectRatio as "1:1" | "3:4" | "4:3" | "9:16" | "16:9",
        },
    });

    const base64ImageBytes = response.generatedImages[0].image.imageBytes;
    return `data:image/png;base64,${base64ImageBytes}`;
};

export const editImage = async (base64Image: string, prompt: string): Promise<string> => {
    const ai = getAi();
    const mimeType = base64Image.substring(base64Image.indexOf(":") + 1, base64Image.indexOf(";"));
    const imageData = base64Image.split(',')[1];

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                { inlineData: { data: imageData, mimeType: mimeType } },
                { text: prompt },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            const base64ImageBytes: string = part.inlineData.data;
            return `data:image/png;base64,${base64ImageBytes}`;
        }
    }
    throw new Error("No image was generated by the model.");
};

export const generateSpeech = async (text: string): Promise<AudioBuffer> => {
    const ai = getAi();
    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-preview-tts",
        contents: [{ parts: [{ text: text }] }],
        config: {
            responseModalities: [Modality.AUDIO],
            speechConfig: {
                voiceConfig: {
                    prebuiltVoiceConfig: { voiceName: 'Kore' },
                },
            },
        },
    });

    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!base64Audio) {
        throw new Error("No audio data received from API.");
    }
    
    // Polyfill for webkitAudioContext
    // FIX: Cast window to any to access webkitAudioContext for older browser compatibility.
    const AudioContext = window.AudioContext || (window as any).webkitAudioContext;
    const outputAudioContext = new AudioContext({ sampleRate: 24000 });

    const decode = (base64: string) => {
        const binaryString = atob(base64);
        const len = binaryString.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
            bytes[i] = binaryString.charCodeAt(i);
        }
        return bytes;
    }

    const decodeAudioData = async (
        data: Uint8Array,
        ctx: AudioContext,
        sampleRate: number,
        numChannels: number,
    ): Promise<AudioBuffer> => {
        const dataInt16 = new Int16Array(data.buffer);
        const frameCount = dataInt16.length / numChannels;
        const buffer = ctx.createBuffer(numChannels, frameCount, sampleRate);

        for (let channel = 0; channel < numChannels; channel++) {
            const channelData = buffer.getChannelData(channel);
            for (let i = 0; i < frameCount; i++) {
                channelData[i] = dataInt16[i * numChannels + channel] / 32768.0;
            }
        }
        return buffer;
    }
    
    const decodedBytes = decode(base64Audio);
    return await decodeAudioData(decodedBytes, outputAudioContext, 24000, 1);
};